name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lua-version: ["5.1", "5.2", "5.3", "5.4", "luajit"]

    name: Lua ${{ matrix.lua-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Lua ${{ matrix.lua-version }}
      uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.lua-version }}

    - name: Set up luarocks
      uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Install dependencies
      run: |
        until luarocks install lualogging
        do
          sleep 1
        done
        until luarocks install busted
        do
          sleep 1
        done
        until luarocks install busted-htest
        do
          sleep 1
        done
        until luarocks install cluacov
        do
          sleep 1
        done
        until luarocks install luacheck
        do
          sleep 1
        done
        until luarocks install luacov-coveralls
        do
          sleep 1 
        done

    - name: Run tests
      run: busted spec -o htest
      
    - name: Reporting test coverage
      run: |
        busted -c -v
        luacov-coveralls -i src -e .luarocks
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
